
package ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.2
 * Fri Mar 08 21:39:58 ART 2019
 * Generated source version: 3.2.2
 */

@XmlRootElement(name = "marcas", namespace = "http://ws.das.edu.ubp.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "marcas", namespace = "http://ws.das.edu.ubp.ar/", propOrder = {"identificador", "marca"})

public class Marcas {

    @XmlElement(name = "identificador")
    private java.lang.String identificador;
    @XmlElement(name = "marca")
    private java.lang.String marca;

    public java.lang.String getIdentificador() {
        return this.identificador;
    }

    public void setIdentificador(java.lang.String newIdentificador)  {
        this.identificador = newIdentificador;
    }

    public java.lang.String getMarca() {
        return this.marca;
    }

    public void setMarca(java.lang.String newMarca)  {
        this.marca = newMarca;
    }

}

