
package ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2019-03-22T18:35:57.589-03:00
 * Generated source version: 3.2.2
 *
 */

public class SupermercadoCXFOne_PortTypeServer{

    protected SupermercadoCXFOne_PortTypeServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ws.SupermercadoCXFOne();
        String address = "http://localhost:9090/SupermercadoCXFOnePort";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new SupermercadoCXFOne_PortTypeServer();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}

