INSERT INTO categoriaProducto (nombre,urlImagen) VALUES
 ('Pan','./../../assets/img/cat_pan.png')
,('Galletitas de agua','./../../assets/img/cat_gal_s.png')
,('Galletitas dulces','./../../assets/img/cat_gal_d.jpg')
,('Arroz','./../../assets/img/cat_arroz.png')
,('Harina de trigo','./../../assets/img/cat_har_t.png')
,('Otras harinas','./../../assets/img/cat_har_o.jpeg')
,('Fideos','./../../assets/img/cat_fideos.jpg')
,('Papa','./../../assets/img/cat_papa.jpg')
,('Batata','./../../assets/img/cat_batata.jpg')
,('Azúcar','./../../assets/img/cat_azucar.png')
,('Dulces','./../../assets/img/cat_dulces.png')
,('Legumbres secas','./../../assets/img/cat_leg_sec.png')
,('Hortalizas','./../../assets/img/cat_hortalizas.jpg')
,('Frutas','./../../assets/img/cat_frutas.png')
,('Carnes','./../../assets/img/cat_carnes.png')
,('Menudencias','./../../assets/img/cat_menud.png')
,('Fiambres','./../../assets/img/cat_fiambres.jpg')
,('Huevos','./../../assets/img/cat_huevos.png')
,('Leche','./../../assets/img/cat_leche.png')
,('Queso','./../../assets/img/cat_quesos.png')
,('Yogur','./../../assets/img/cat_yogur.png')
,('Manteca','./../../assets/img/cat_manteca.png')
,('Aceite','./../../assets/img/cat_aceite.png')
,('Bebidas no alcohólicas','./../../assets/img/cat_beb_na.jpg')
,('Bebidas alcohólicas','./../../assets/img/cat_beb_a.png')
,('Sal fina','./../../assets/img/cat_sal.jpg')
,('Condimentos','./../../assets/img/cat_condim.png')
,('Vinagre','./../../assets/img/cat_vinagre.png')
,('Café','./../../assets/img/cat_cafe.png')
,('Yerba','./../../assets/img/cat_yerba.png')

