INSERT INTO ingrediente (idIngrediente, nombreIngrediente)
VALUES
 (1, 'Pan de Hamburguesa')
,(2, 'Pan de Pancho')
,(3, 'Galletita Saladas')
,(4, 'Galletitas Dulces')
,(5, 'Arroz Blanco')
,(6, 'Pechuga Pollo')
,(7, 'Leche')
,(8, 'Harina de Trigo 000')
,(9, 'Huevo')
,(10, 'Crema de Leche')
,(11, 'Queso Rallado')
,(12, 'Aceite de Girasol')
,(13, 'Aji Molido')
,(14, 'Sal Fina')
,(15, 'Pimienta Negra Molida')
,(16, 'Cebolla')
,(17, 'Zanahoria')
,(18, 'Perejil Deshidratado')
,(19, 'Pimienta Blanca Molida')
,(20, 'Oregano')
,(21, 'Poroto Alubia')
,(22, 'Arveja Seca')
,(23, 'Ajo Deshidratado')
,(24, 'Tomate Pelado')
,(25, 'Garbanzo Seco')
,(26, 'Limon')
,(27, 'Sesamo')
,(28, 'Caldo Para Verduras')
,(29, 'Comino Molido')
,(30, 'Pimenton')
,(31, 'Tallarines')
,(32, 'Jamon Cocido')
,(33, 'Margarina')
,(34, 'Bistec')
,(35, 'Atun En Lomitos')
,(36, 'Pan Rallado')
,(37, 'Ricota')
,(38, 'Espinaca')
,(39, 'Berenjena')
,(40, 'Provenzal')
,(41, 'Queso Cremoso')
,(42, 'Vinagre')
,(43, 'Zapallo')
,(44, 'Carne Molida')
,(45, 'Queso Dambo')
,(46, 'Tapa de Empanada')
,(47, 'Pimiento Rojo')
,(48, 'Pata Pollo')
,(49, 'Vino Blanco')
,(50, 'Papa blanca')


