INSERT INTO ingrediente (idIngrediente, nombreIngrediente)
VALUES
(1,'Pan de Hamburguesa')
,(2,'Pan de Pancho')
,(3,'Galletita Saladas')
,(4,'Galletitas Dulces')
,(5,'Arroz Blanco')
,(6,'Pechuga Pollo')
,(7,'Leche')
,(8,'Harina de Trigo 000')
,(9,'Huevo')
,(10,'Crema de Leche')
,(11,'Queso Rallado')
,(12,'Aceite de Girasol')
,(13,'Aji Molido')
,(14,'Sal Fina')
,(15,'Pimienta Negra Molida')