INSERT INTO localidad (idProvincia,nombre) VALUES -- CATAMARCA
(2,'Ancasti'),
(2,'Andalgalá'),
(2,'Antofagasta'),
(2,'Belén'),
(2,'Capayán'),
(2,'Capital'),
(2,'Corral Quemado'),
(2,'El Alto'),
(2,'El Rodeo'),
(2,'F.Mamerto Esquiú'),
(2,'Fiambalá'),
(2,'Hualfín'),
(2,'Huillapima'),
(2,'Icaño'),
(2,'La Puerta'),
(2,'Las Juntas'),
(2,'Londres'),
(2,'Los Altos'),
(2,'Los Varela'),
(2,'Mutquín'),
(2,'Paclín'),
(2,'Poman'),
(2,'Pozo de La Piedra'),
(2,'Puerta de Corral'),
(2,'Puerta San José'),
(2,'Recreo'),
(2,'S.F.V de 4'),
(2,'San Fernando'),
(2,'San Fernando del Valle'),
(2,'San José'),
(2,'Santa María'),
(2,'Santa Rosa'),
(2,'Saujil'),
(2,'Tapso'),
(2,'Tinogasta'),
(2,'Valle Viejo'),
(2,'Villa Vil')
GO


INSERT INTO localidad (idProvincia,nombre) VALUES -- CHACO
(3,'Aviá Teraí'),
(3,'Barranqueras'),
(3,'Basail'),
(3,'Campo Largo'),
(3,'Capital'),
(3,'Capitán Solari'),
(3,'Charadai'),
(3,'Charata'),
(3,'Chorotis'),
(3,'Ciervo Petiso'),
(3,'Cnel. Du Graty'),
(3,'Col. Benítez'),
(3,'Col. Elisa'),
(3,'Col. Popular'),
(3,'Colonias Unidas'),
(3,'Concepción'),
(3,'Corzuela'),
(3,'Cote Lai'),
(3,'El Sauzalito'),
(3,'Enrique Urien'),
(3,'Fontana'),
(3,'Fte. Esperanza'),
(3,'Gancedo'),
(3,'Gral. Capdevila'),
(3,'Gral. Pinero'),
(3,'Gral. San Martín'),
(3,'Gral. Vedia'),
(3,'Hermoso Campo'),
(3,'I. del Cerrito'),
(3,'J.J. Castelli'),
(3,'La Clotilde'),
(3,'La Eduvigis'),
(3,'La Escondida'),
(3,'La Leonesa'),
(3,'La Tigra'),
(3,'La Verde'),
(3,'Laguna Blanca'),
(3,'Laguna Limpia'),
(3,'Lapachito'),
(3,'Las Breñas'),
(3,'Las Garcitas'),
(3,'Las Palmas'),
(3,'Los Frentones'),
(3,'Machagai'),
(3,'Makallé'),
(3,'Margarita Belén'),
(3,'Miraflores'),
(3,'Misión N. Pompeya'),
(3,'Napenay'),
(3,'Pampa Almirón'),
(3,'Pampa del Indio'),
(3,'Pampa del Infierno'),
(3,'Pdcia. de La Plaza'),
(3,'Pdcia. Roca'),
(3,'Pdcia. Roque Sáenz Peña'),
(3,'Pto. Bermejo'),
(3,'Pto. Eva Perón'),
(3,'Puero Tirol'),
(3,'Puerto Vilelas'),
(3,'Quitilipi'),
(3,'Resistencia'),
(3,'Sáenz Peña'),
(3,'Samuhú'),
(3,'San Bernardo'),
(3,'Santa Sylvina'),
(3,'Taco Pozo'),
(3,'Tres Isletas'),
(3,'Villa Ángela'),
(3,'Villa Berthet'),
(3,'Villa R. Bermejito')
GO

INSERT INTO localidad (idProvincia,nombre) VALUES -- CHUBUT
(4,'Aldea Apeleg'),
(4,'Aldea Beleiro'),
(4,'Aldea Epulef'),
(4,'Alto Río Sengerr'),
(4,'Buen Pasto'),
(4,'Camarones'),
(4,'Carrenleufú'),
(4,'Cholila'),
(4,'Co. Centinela'),
(4,'Colan Conhué'),
(4,'Comodoro Rivadavia'),
(4,'Corcovado'),
(4,'Cushamen'),
(4,'Dique F. Ameghino'),
(4,'Dolavón'),
(4,'Dr. R. Rojas'),
(4,'El Hoyo'),
(4,'El Maitén'),
(4,'Epuyén'),
(4,'Esquel'),
(4,'Facundo'),
(4,'Gaimán'),
(4,'Gan Gan'),
(4,'Gastre'),
(4,'Gdor. Costa'),
(4,'Gualjaina'),
(4,'J. de San Martín'),
(4,'Lago Blanco'),
(4,'Lago Puelo'),
(4,'Lagunita Salada'),
(4,'Las Plumas'),
(4,'Los Altares'),
(4,'Paso de los Indios'),
(4,'Paso del Sapo'),
(4,'Pto. Madryn'),
(4,'Pto. Pirámides'),
(4,'Rada Tilly'),
(4,'Rawson'),
(4,'Río Mayo'),
(4,'Río Pico'),
(4,'Sarmiento'),
(4,'Tecka'),
(4,'Telsen'),
(4,'Trelew'),
(4,'Trevelin'),
(4,'Veintiocho de Julio')
GO


INSERT INTO localidad (idProvincia,nombre) VALUES -- CORDOBA
(5, 'Achiras'),
(5, 'Adelia Maria'),
(5, 'Agua de Oro'),
(5, 'Alcira Gigena'),
(5, 'Aldea Santa Maria'),
(5, 'Alejandro Roca'),
(5, 'Alejo Ledesma'),
(5, 'Alicia'),
(5, 'Almafuerte'),
(5, 'Alpa Corral'),
(5, 'Alta Gracia'),
(5, 'Alto Alegre'),
(5, 'Alto de Los Quebrachos'),
(5, 'Altos de Chipion'),
(5, 'Amboy'),
(5, 'Ambul'),
(5, 'Ana Zumaran'),
(5, 'Anisacate'),
(5, 'Arguello'),
(5, 'Arias'),
(5, 'Arroyito'),
(5, 'Arroyo Algodon'),
(5, 'Arroyo Cabral'),
(5, 'Arroyo Los Patos'),
(5, 'Assunta'),
(5, 'Atahona'),
(5, 'Ausonia'),
(5, 'Avellaneda'),
(5, 'Ballesteros'),
(5, 'Ballesteros Sud'),
(5, 'Balnearia'),
(5, 'Bañado de Soto'),
(5, 'Bell Ville'),
(5, 'Bengolea'),
(5, 'Benjamin Gould'),
(5, 'Berrotaran'),
(5, 'Bialet Masse'),
(5, 'Bouwer'),
(5, 'Brinkmann'),
(5, 'Buchardo'),
(5, 'Bulnes'),
(5, 'Cabalango'),
(5, 'Calamuchita'),
(5, 'Calchin'),
(5, 'Calchin Oeste'),
(5, 'Calmayo'),
(5, 'Camilo Aldao'),
(5, 'Caminiaga'),
(5, 'Cañada de Luque'),
(5, 'Cañada de Machado'),
(5, 'Cañada de Rio Pinto'),
(5, 'Cañada del Sauce'),
(5, 'Canals'),
(5, 'Candelaria Sud'),
(5, 'Capilla de Remedios'),
(5, 'Capilla de Siton'),
(5, 'Capilla del Carmen'),
(5, 'Capilla del Monte'),
(5, 'Capital'),
(5, 'Capitan Gral B. O´Higgins'),
(5, 'Carnerillo'),
(5, 'Carrilobo'),
(5, 'Casa Grande'),
(5, 'Cavanagh'),
(5, 'Cerro Colorado'),
(5, 'Chaján'),
(5, 'Chalacea'),
(5, 'Chañar Viejo'),
(5, 'Chancaní'),
(5, 'Charbonier'),
(5, 'Charras'),
(5, 'Chazón'),
(5, 'Chilibroste'),
(5, 'Chucul'),
(5, 'Chuña'),
(5, 'Chuña Huasi'),
(5, 'Churqui Cañada'),
(5, 'Cienaga Del Coro'),
(5, 'Cintra'),
(5, 'Col. Almada'),
(5, 'Col. Anita'),
(5, 'Col. Barge'),
(5, 'Col. Bismark'),
(5, 'Col. Bremen'),
(5, 'Col. Caroya'),
(5, 'Col. Italiana'),
(5, 'Col. Iturraspe'),
(5, 'Col. Las Cuatro Esquinas'),
(5, 'Col. Las Pichanas'),
(5, 'Col. Marina'),
(5, 'Col. Prosperidad'),
(5, 'Col. San Bartolome'),
(5, 'Col. San Pedro'),
(5, 'Col. Tirolesa'),
(5, 'Col. Vicente Aguero'),
(5, 'Col. Videla'),
(5, 'Col. Vignaud'),
(5, 'Col. Waltelina'),
(5, 'Colazo'),
(5, 'Comechingones'),
(5, 'Conlara'),
(5, 'Copacabana'),
(5, 'Coronel Baigorria'),
(5, 'Coronel Moldes'),
(5, 'Corral de Bustos'),
(5, 'Corralito'),
(5, 'Cosquín'),
(5, 'Costa Sacate'),
(5, 'Cruz Alta'),
(5, 'Cruz de Caña'),
(5, 'Cruz del Eje'),
(5, 'Cuesta Blanca'),
(5, 'Dean Funes'),
(5, 'Del Campillo'),
(5, 'Despeñaderos'),
(5, 'Devoto'),
(5, 'Diego de Rojas'),
(5, 'Dique Chico'),
(5, 'El Arañado'),
(5, 'El Brete'),
(5, 'El Chacho'),
(5, 'El Crispín'),
(5, 'El Fortín'),
(5, 'El Manzano'),
(5, 'El Rastreador'),
(5, 'El Rodeo'),
(5, 'El Tío'),
(5, 'Elena'),
(5, 'Embalse'),
(5, 'Esquina'),
(5, 'Estación Gral. Paz'),
(5, 'Estación Juárez Celman'),
(5, 'Estancia de Guadalupe'),
(5, 'Estancia Vieja'),
(5, 'Etruria'),
(5, 'Eufrasio Loza'),
(5, 'Falda del Carmen'),
(5, 'Freyre'),
(5, 'Gral. Baldissera'),
(5, 'Gral. Cabrera'),
(5, 'Gral. Deheza'),
(5, 'Gral. Fotheringham'),
(5, 'Gral. Levalle'),
(5, 'Gral. Roca'),
(5, 'Guanaco Muerto'),
(5, 'Guasapampa'),
(5, 'Guatimozin'),
(5, 'Gutenberg'),
(5, 'Hernando'),
(5, 'Huanchillas'),
(5, 'Huerta Grande'),
(5, 'Huinca Renanco'),
(5, 'Idiazabal'),
(5, 'Impira'),
(5, 'Inriville'),
(5, 'Isla Verde'),
(5, 'Italó'),
(5, 'James Craik'),
(5, 'Jesús María'),
(5, 'Jovita'),
(5, 'Justiniano Posse'),
(5, 'Km 658'),
(5, 'L. V. Mansilla'),
(5, 'La Batea'),
(5, 'La Calera'),
(5, 'La Carlota'),
(5, 'La Carolina'),
(5, 'La Cautiva'),
(5, 'La Cesira'),
(5, 'La Cruz'),
(5, 'La Cumbre'),
(5, 'La Cumbrecita'),
(5, 'La Falda'),
(5, 'La Francia'),
(5, 'La Granja'),
(5, 'La Higuera'),
(5, 'La Laguna'),
(5, 'La Paisanita'),
(5, 'La Palestina'),
(5, '12'),
(5, 'La Paquita'),
(5, 'La Para'),
(5, 'La Paz'),
(5, 'La Playa'),
(5, 'La Playosa'),
(5, 'La Población'),
(5, 'La Posta'),
(5, 'La Puerta'),
(5, 'La Quinta'),
(5, 'La Rancherita'),
(5, 'La Rinconada'),
(5, 'La Serranita'),
(5, 'La Tordilla'),
(5, 'Laborde'),
(5, 'Laboulaye'),
(5, 'Laguna Larga'),
(5, 'Las Acequias'),
(5, 'Las Albahacas'),
(5, 'Las Arrias'),
(5, 'Las Bajadas'),
(5, 'Las Caleras'),
(5, 'Las Calles'),
(5, 'Las Cañadas'),
(5, 'Las Gramillas'),
(5, 'Las Higueras'),
(5, 'Las Isletillas'),
(5, 'Las Junturas'),
(5, 'Las Palmas'),
(5, 'Las Peñas'),
(5, 'Las Peñas Sud'),
(5, 'Las Perdices'),
(5, 'Las Playas'),
(5, 'Las Rabonas'),
(5, 'Las Saladas'),
(5, 'Las Tapias'),
(5, 'Las Varas'),
(5, 'Las Varillas'),
(5, 'Las Vertientes'),
(5, 'Leguizamón'),
(5, 'Leones'),
(5, 'Los Cedros'),
(5, 'Los Cerrillos'),
(5, 'Los Chañaritos (C.E)'),
(5, 'Los Chanaritos (R.S)'),
(5, 'Los Cisnes'),
(5, 'Los Cocos'),
(5, 'Los Cóndores'),
(5, 'Los Hornillos'),
(5, 'Los Hoyos'),
(5, 'Los Mistoles'),
(5, 'Los Molinos'),
(5, 'Los Pozos'),
(5, 'Los Reartes'),
(5, 'Los Surgentes'),
(5, 'Los Talares'),
(5, 'Los Zorros'),
(5, 'Lozada'),
(5, 'Luca'),
(5, 'Luque'),
(5, 'Luyaba'),
(5, 'Malagueño'),
(5, 'Malena'),
(5, 'Malvinas Argentinas'),
(5, 'Manfredi'),
(5, 'Maquinista Gallini'),
(5, 'Marcos Juárez'),
(5, 'Marull'),
(5, 'Matorrales'),
(5, 'Mattaldi'),
(5, 'Mayu Sumaj'),
(5, 'Media Naranja'),
(5, 'Melo'),
(5, 'Mendiolaza'),
(5, 'Mi Granja'),
(5, 'Mina Clavero'),
(5, 'Miramar'),
(5, 'Morrison'),
(5, 'Morteros'),
(5, 'Mte. Buey'),
(5, 'Mte. Cristo'),
(5, 'Mte. De Los Gauchos'),
(5, 'Mte. Leña'),
(5, 'Mte. Maíz'),
(5, 'Mte. Ralo'),
(5, 'Nicolás Bruzone'),
(5, 'Noetinger'),
(5, 'Nono'),
(5, 'Nueva 7'),
(5, 'Obispo Trejo'),
(5, 'Olaeta'),
(5, 'Oliva'),
(5, 'Olivares San Nicolás'),
(5, 'Onagolty'),
(5, 'Oncativo'),
(5, 'Ordoñez'),
(5, 'Pacheco De Melo'),
(5, 'Pampayasta N.'),
(5, 'Pampayasta S.'),
(5, 'Panaholma'),
(5, 'Pascanas'),
(5, 'Pasco'),
(5, 'Paso del Durazno'),
(5, 'Paso Viejo'),
(5, 'Pilar'),
(5, 'Pincén'),
(5, 'Piquillín'),
(5, 'Plaza de Mercedes'),
(5, 'Plaza Luxardo'),
(5, 'Porteña'),
(5, 'Potrero de Garay'),
(5, 'Pozo del Molle'),
(5, 'Pozo Nuevo'),
(5, 'Pueblo Italiano'),
(5, 'Puesto de Castro'),
(5, 'Punta del Agua'),
(5, 'Quebracho Herrado'),
(5, 'Quilino'),
(5, 'Rafael García'),
(5, 'Ranqueles'),
(5, 'Rayo Cortado'),
(5, 'Reducción'),
(5, 'Rincón'),
(5, 'Río Bamba'),
(5, 'Río Ceballos'),
(5, 'Río Cuarto'),
(5, 'Río de Los Sauces'),
(5, 'Río Primero'),
(5, 'Río Segundo'),
(5, 'Río Tercero'),
(5, 'Rosales'),
(5, 'Rosario del Saladillo'),
(5, 'Sacanta'),
(5, 'Sagrada Familia'),
(5, 'Saira'),
(5, 'Saladillo'),
(5, 'Saldán'),
(5, 'Salsacate'),
(5, 'Salsipuedes'),
(5, 'Sampacho'),
(5, 'San Agustín'),
(5, 'San Antonio de Arredondo'),
(5, 'San Antonio de Litín'),
(5, 'San Basilio'),
(5, 'San Carlos Minas'),
(5, 'San Clemente'),
(5, 'San Esteban'),
(5, 'San Francisco'),
(5, 'San Ignacio'),
(5, 'San Javier'),
(5, 'San Jerónimo'),
(5, 'San Joaquín'),
(5, 'San José de La Dormida'),
(5, 'San José de Las Salinas'),
(5, 'San Lorenzo'),
(5, 'San Marcos Sierras'),
(5, 'San Marcos Sud'),
(5, 'San Pedro'),
(5, 'San Pedro N.'),
(5, 'San Roque'),
(5, 'San Vicente'),
(5, 'Santa Catalina'),
(5, 'Santa Elena'),
(5, 'Santa Eufemia'),
(5, 'Santa Maria'),
(5, 'Sarmiento'),
(5, 'Saturnino M.Laspiur'),
(5, 'Sauce Arriba'),
(5, 'Sebastián Elcano'),
(5, 'Seeber'),
(5, 'Segunda Usina'),
(5, 'Serrano'),
(5, 'Serrezuela'),
(5, 'Sgo. Temple'),
(5, 'Silvio Pellico'),
(5, 'Simbolar'),
(5, 'Sinsacate'),
(5, 'Sta. Rosa de Calamuchita'),
(5, 'Sta. Rosa de Río Primero'),
(5, 'Suco'),
(5, 'Tala Cañada'),
(5, 'Tala Huasi'),
(5, 'Talaini'),
(5, 'Tancacha'),
(5, 'Tanti'),
(5, 'Ticino'),
(5, 'Tinoco'),
(5, 'Tío Pujio'),
(5, 'Toledo'),
(5, 'Toro Pujio'),
(5, 'Tosno'),
(5, 'Tosquita'),
(5, 'Tránsito'),
(5, 'Tuclame'),
(5, 'Tutti'),
(5, 'Ucacha'),
(5, 'Unquillo'),
(5, 'Valle de Anisacate'),
(5, 'Valle Hermoso'),
(5, 'Vélez Sarfield'),
(5, 'Viamonte'),
(5, 'Vicuña Mackenna'),
(5, 'Villa Allende'),
(5, 'Villa Amancay'),
(5, 'Villa Ascasubi'),
(5, 'Villa Candelaria N.'),
(5, 'Villa Carlos Paz'),
(5, 'Villa Cerro Azul'),
(5, 'Villa Ciudad de América'),
(5, 'Villa Ciudad Pque Los Reartes'),
(5, 'Villa Concepción del Tío'),
(5, 'Villa Cura Brochero'),
(5, 'Villa de Las Rosas'),
(5, 'Villa de María'),
(5, 'Villa de Pocho'),
(5, 'Villa de Soto'),
(5, 'Villa del Dique'),
(5, 'Villa del Prado'),
(5, 'Villa del Rosario'),
(5, 'Villa del Totoral'),
(5, 'Villa Dolores'),
(5, 'Villa El Chancay'),
(5, 'Villa Elisa'),
(5, 'Villa Flor Serrana'),
(5, 'Villa Fontana'),
(5, 'Villa Giardino'),
(5, 'Villa Gral. Belgrano'),
(5, 'Villa Gutierrez'),
(5, 'Villa Huidobro'),
(5, 'Villa La Bolsa'),
(5, 'Villa Los Aromos'),
(5, 'Villa Los Patos'),
(5, 'Villa María'),
(5, 'Villa Nueva'),
(5, 'Villa Pque. Santa Ana'),
(5, 'Villa Pque. Siquiman'),
(5, 'Villa Quillinzo'),
(5, 'Villa Rossi'),
(5, 'Villa Rumipal'),
(5, 'Villa San Esteban'),
(5, 'Villa San Isidro'),
(5, 'Villa 21'),
(5, 'Villa Sarmiento (G.R)'),
(5, 'Villa Sarmiento (S.A)'),
(5, 'Villa Tulumba'),
(5, 'Villa Valeria'),
(5, 'Villa Yacanto'),
(5, 'Washington'),
(5, 'Wenceslao Escalante'),
(5, 'Ycho Cruz Sierras')
GO

INSERT INTO localidad (idProvincia,nombre) VALUES -- CORRIENTES
(6,'Alvear'),
(6,'Bella Vista'),
(6,'Berón de Astrada'),
(6,'Bonpland'),
(6,'Caá Cati'),
(6,'Capital'),
(6,'Chavarría'),
(6,'Col. C. Pellegrini'),
(6,'Col. Libertad'),
(6,'Col. Liebig'),
(6,'Col. Sta Rosa'),
(6,'Concepción'),
(6,'Cruz de Los Milagros'),
(6,'Curuzú-Cuatiá'),
(6,'Empedrado'),
(6,'Esquina'),
(6,'Estación Torrent'),
(6,'Felipe Yofré'),
(6,'Garruchos'),
(6,'Gdor. Agrónomo'),
(6,'Gdor. Martínez'),
(6,'Goya'),
(6,'Guaviravi'),
(6,'Herlitzka'),
(6,'Ita-Ibate'),
(6,'Itatí'),
(6,'Ituzaingó'),
(6,'José Rafael Gómez'),
(6,'Juan Pujol'),
(6,'La Cruz'),
(6,'Lavalle'),
(6,'Lomas de Vallejos'),
(6,'Loreto'),
(6,'Mariano I. Loza'),
(6,'Mburucuyá'),
(6,'Mercedes'),
(6,'Mocoretá'),
(6,'Mte. Caseros'),
(6,'Nueve de Julio'),
(6,'Palmar Grande'),
(6,'Parada Pucheta'),
(6,'Paso de La Patria'),
(6,'Paso de Los Libres'),
(6,'Pedro R. Fernandez'),
(6,'Perugorría'),
(6,'Pueblo Libertador'),
(6,'Ramada Paso'),
(6,'Riachuelo'),
(6,'Saladas'),
(6,'San Antonio'),
(6,'San Carlos'),
(6,'San Cosme'),
(6,'San Lorenzo'),
(6,'20 del Palmar'),
(6,'San Miguel'),
(6,'San Roque'),
(6,'Santa Ana'),
(6,'Santa Lucía'),
(6,'Santo Tomé'),
(6,'Sauce'),
(6,'Tabay'),
(6,'Tapebicuá'),
(6,'Tatacua'),
(6,'Virasoro'),
(6,'Yapeyú'),
(6,'Yataití Calle')
GO


INSERT INTO localidad (idProvincia,nombre) VALUES -- ENTRE RIOS
(7,'Alarcón'),
(7,'Alcaraz'),
(7,'Alcaraz N.'),
(7,'Alcaraz S.'),
(7,'Aldea Asunción'),
(7,'Aldea Brasilera'),
(7,'Aldea Elgenfeld'),
(7,'Aldea Grapschental'),
(7,'Aldea Ma. Luisa'),
(7,'Aldea Protestante'),
(7,'Aldea Salto'),
(7,'Aldea San Antonio (G)'),
(7,'Aldea San Antonio (P)'),
(7,'Aldea 19'),
(7,'Aldea San Miguel'),
(7,'Aldea San Rafael'),
(7,'Aldea Spatzenkutter'),
(7,'Aldea Sta. María'),
(7,'Aldea Sta. Rosa'),
(7,'Aldea Valle María'),
(7,'Altamirano Sur'),
(7,'Antelo'),
(7,'Antonio Tomás'),
(7,'Aranguren'),
(7,'Arroyo Barú'),
(7,'Arroyo Burgos'),
(7,'Arroyo Clé'),
(7,'Arroyo Corralito'),
(7,'Arroyo del Medio'),
(7,'Arroyo Maturrango'),
(7,'Arroyo Palo Seco'),
(7,'Banderas'),
(7,'Basavilbaso'),
(7,'Betbeder'),
(7,'Bovril'),
(7,'Caseros'),
(7,'Ceibas'),
(7,'Cerrito'),
(7,'Chajarí'),
(7,'Chilcas'),
(7,'Clodomiro Ledesma'),
(7,'Col. Alemana'),
(7,'Col. Avellaneda'),
(7,'Col. Avigdor'),
(7,'Col. Ayuí'),
(7,'Col. Baylina'),
(7,'Col. Carrasco'),
(7,'Col. Celina'),
(7,'Col. Cerrito'),
(7,'Col. Crespo'),
(7,'Col. Elia'),
(7,'Col. Ensayo'),
(7,'Col. Gral. Roca'),
(7,'Col. La Argentina'),
(7,'Col. Merou'),
(7,'Col. Oficial Nª3'),
(7,'Col. Oficial Nº13'),
(7,'Col. Oficial Nº14'),
(7,'Col. Oficial Nº5'),
(7,'Col. Reffino'),
(7,'Col. Tunas'),
(7,'Col. Viraró'),
(7,'Colón'),
(7,'Concepción del Uruguay'),
(7,'Concordia'),
(7,'Conscripto Bernardi'),
(7,'Costa Grande'),
(7,'Costa San Antonio'),
(7,'Costa Uruguay N.'),
(7,'Costa Uruguay S.'),
(7,'Crespo'),
(7,'Crucecitas 3ª'),
(7,'Crucecitas 7ª'),
(7,'Crucecitas 8ª'),
(7,'Cuchilla Redonda'),
(7,'Curtiembre'),
(7,'Diamante'),
(7,'Distrito 6º'),
(7,'Distrito Chañar'),
(7,'Distrito Chiqueros'),
(7,'Distrito Cuarto'),
(7,'Distrito Diego López'),
(7,'Distrito Pajonal'),
(7,'Distrito Sauce'),
(7,'Distrito Tala'),
(7,'Distrito Talitas'),
(7,'Don Cristóbal 1ª Sección'),
(7,'Don Cristóbal 2ª Sección'),
(7,'Durazno'),
(7,'El Cimarrón'),
(7,'El Gramillal'),
(7,'El Palenque'),
(7,'El Pingo'),
(7,'El Quebracho'),
(7,'El Redomón'),
(7,'El Solar'),
(7,'Enrique Carbo'),
(7,'Espinillo N.'),
(7,'Estación Campos'),
(7,'Estación Escriña'),
(7,'Estación Lazo'),
(7,'Estación Raíces'),
(7,'Estación Yerúa'),
(7,'Estancia Grande'),
(7,'Estancia Líbaros'),
(7,'Estancia Racedo'),
(7,'Estancia Solá'),
(7,'Estancia Yuquerí'),
(7,'Estaquitas'),
(7,'Faustino M. Parera'),
(7,'Febre'),
(7,'Federación'),
(7,'Federal'),
(7,'Gdor. Echagüe'),
(7,'Gdor. Mansilla'),
(7,'Gilbert'),
(7,'González Calderón'),
(7,'Gral. Almada'),
(7,'Gral. Alvear'),
(7,'Gral. Campos'),
(7,'Gral. Galarza'),
(7,'Gral. Ramírez'),
(7,'Gualeguay'),
(7,'Gualeguaychú'),
(7,'Gualeguaycito'),
(7,'Guardamonte'),
(7,'Hambis'),
(7,'Hasenkamp'),
(7,'Hernandarias'),
(7,'Hernández'),
(7,'Herrera'),
(7,'Hinojal'),
(7,'Hocker'),
(7,'Ing. Sajaroff'),
(7,'Irazusta'),
(7,'Isletas'),
(7,'J.J De Urquiza'),
(7,'Jubileo'),
(7,'La Clarita'),
(7,'La Criolla'),
(7,'La Esmeralda'),
(7,'La Florida'),
(7,'La Fraternidad'),
(7,'La Hierra'),
(7,'La Ollita'),
(7,'La Paz'),
(7,'La Picada'),
(7,'La Providencia'),
(7,'La Verbena'),
(7,'Laguna Benítez'),
(7,'Larroque'),
(7,'Las Cuevas'),
(7,'Las Garzas'),
(7,'Las Guachas'),
(7,'Las Mercedes'),
(7,'Las Moscas'),
(7,'Las Mulitas'),
(7,'Las Toscas'),
(7,'Laurencena'),
(7,'Libertador San Martín'),
(7,'Loma Limpia'),
(7,'Los Ceibos'),
(7,'Los Charruas'),
(7,'Los Conquistadores'),
(7,'Lucas González'),
(7,'Lucas N.'),
(7,'Lucas S. 1ª'),
(7,'Lucas S. 2ª'),
(7,'Maciá'),
(7,'María Grande'),
(7,'María Grande 2ª'),
(7,'Médanos'),
(7,'Mojones N.'),
(7,'Mojones S.'),
(7,'Molino Doll'),
(7,'Monte Redondo'),
(7,'Montoya'),
(7,'Mulas Grandes'),
(7,'Ñancay'),
(7,'Nogoyá'),
(7,'Nueva Escocia'),
(7,'Nueva Vizcaya'),
(7,'Ombú'),
(7,'Oro Verde'),
(7,'Paraná'),
(7,'Pasaje Guayaquil'),
(7,'Pasaje Las Tunas'),
(7,'Paso de La Arena'),
(7,'Paso de La Laguna'),
(7,'Paso de Las Piedras'),
(7,'Paso Duarte'),
(7,'Pastor Britos'),
(7,'Pedernal'),
(7,'Perdices'),
(7,'Picada Berón'),
(7,'Piedras Blancas'),
(7,'Primer Distrito Cuchilla'),
(7,'Primero de Mayo'),
(7,'Pronunciamiento'),
(7,'Pto. Algarrobo'),
(7,'Pto. Ibicuy'),
(7,'Pueblo Brugo'),
(7,'Pueblo Cazes'),
(7,'Pueblo Gral. Belgrano'),
(7,'Pueblo Liebig'),
(7,'Puerto Yeruá'),
(7,'Punta del Monte'),
(7,'Quebracho'),
(7,'Quinto Distrito'),
(7,'Raices Oeste'),
(7,'Rincón de Nogoyá'),
(7,'Rincón del Cinto'),
(7,'Rincón del Doll'),
(7,'Rincón del Gato'),
(7,'Rocamora'),
(7,'Rosario del Tala'),
(7,'San Benito'),
(7,'San Cipriano'),
(7,'San Ernesto'),
(7,'San Gustavo'),
(7,'San Jaime'),
(7,'San José'),
(7,'San José de Feliciano'),
(7,'San Justo'),
(7,'San Marcial'),
(7,'San Pedro'),
(7,'San Ramírez'),
(7,'San Ramón'),
(7,'San Roque'),
(7,'San Salvador'),
(7,'San Víctor'),
(7,'Santa Ana'),
(7,'Santa Anita'),
(7,'Santa Elena'),
(7,'Santa Lucía'),
(7,'Santa Luisa'),
(7,'Sauce de Luna'),
(7,'Sauce Montrull'),
(7,'Sauce Pinto'),
(7,'Sauce Sur'),
(7,'Seguí'),
(7,'Sir Leonard'),
(7,'Sosa'),
(7,'Tabossi'),
(7,'Tezanos Pinto'),
(7,'Ubajay'),
(7,'Urdinarrain'),
(7,'Veinte de Septiembre'),
(7,'Viale'),
(7,'Victoria'),
(7,'Villa Clara'),
(7,'Villa del Rosario'),
(7,'Villa Domínguez'),
(7,'Villa Elisa'),
(7,'Villa Fontana'),
(7,'Villa Gdor. Etchevehere'),
(7,'Villa Mantero'),
(7,'Villa Paranacito'),
(7,'Villa Urquiza'),
(7,'Villaguay'),
(7,'Walter Moss'),
(7,'Yacaré'),
(7,'Yeso Oeste')
GO

INSERT INTO localidad (idProvincia,nombre) VALUES -- FORMOSA
(8,'Buena Vista'),
(8,'Clorinda'),
(8,'Col. Pastoril'),
(8,'Cte. Fontana'),
(8,'El Colorado'),
(8,'El Espinillo'),
(8,'Estanislao Del Campo'),
(8,'Fortín Lugones'),
(8,'Gral. Lucio V. Mansilla'),
(8,'Gral. Manuel Belgrano'),
(8,'Gral. Mosconi'),
(8,'Gran Guardia'),
(8,'Herradura'),
(8,'Ibarreta'),
(8,'Ing. Juárez'),
(8,'Laguna Blanca'),
(8,'Laguna Naick Neck'),
(8,'Laguna Yema'),
(8,'Las Lomitas'),
(8,'Los Chiriguanos'),
(8,'Mayor V. Villafañe'),
(8,'Misión San Fco.'),
(8,'Palo Santo'),
(8,'Pirané'),
(8,'Pozo del Maza'),
(8,'Riacho He-He'),
(8,'San Hilario'),
(8,'San Martín II'),
(8,'Siete Palmas'),
(8,'Subteniente Perín'),
(8,'Tres Lagunas'),
(8,'Villa Dos Trece'),
(8,'Villa Escolar'),
(8,'Villa Gral. Güemes')
GO

INSERT INTO localidad (idProvincia,nombre) VALUES -- JUJUY
(9,'Abdon Castro Tolay'),
(9,'Abra Pampa'),
(9,'Abralaite'),
(9,'Aguas Calientes'),
(9,'Arrayanal'),
(9,'Barrios'),
(9,'Caimancito'),
(9,'Calilegua'),
(9,'Cangrejillos'),
(9,'Caspala'),
(9,'Catuá'),
(9,'Cieneguillas'),
(9,'Coranzulli'),
(9,'Cusi-Cusi'),
(9,'El Aguilar'),
(9,'El Carmen'),
(9,'El Cóndor'),
(9,'El Fuerte'),
(9,'El Piquete'),
(9,'El Talar'),
(9,'Fraile Pintado'),
(9,'Hipólito Yrigoyen'),
(9,'Huacalera'),
(9,'Humahuaca'),
(9,'La Esperanza'),
(9,'La Mendieta'),
(9,'La Quiaca'),
(9,'Ledesma'),
(9,'Libertador Gral. San Martin'),
(9,'Maimara'),
(9,'Mina Pirquitas'),
(9,'Monterrico'),
(9,'Palma Sola'),
(9,'Palpalá'),
(9,'Pampa Blanca'),
(9,'Pampichuela'),
(9,'Perico'),
(9,'Puesto del Marqués'),
(9,'Puesto Viejo'),
(9,'Pumahuasi'),
(9,'Purmamarca'),
(9,'Rinconada'),
(9,'Rodeitos'),
(9,'Rosario de Río Grande'),
(9,'San Antonio'),
(9,'San Francisco'),
(9,'San Pedro'),
(9,'San Rafael'),
(9,'San Salvador'),
(9,'Santa Ana'),
(9,'Santa Catalina'),
(9,'Santa Clara'),
(9,'Susques'),
(9,'Tilcara'),
(9,'Tres Cruces'),
(9,'Tumbaya'),
(9,'Valle Grande'),
(9,'Vinalito'),
(9,'Volcán'),
(9,'Yala'),
(9,'Yaví'),
(9,'Yuto')
GO

INSERT INTO localidad (idProvincia,nombre) VALUES -- LA PAMPA
(10,'Abramo'),
(10,'Adolfo Van Praet'),
(10,'Agustoni'),
(10,'Algarrobo del Aguila'),
(10,'Alpachiri'),
(10,'Alta Italia'),
(10,'Anguil'),
(10,'Arata'),
(10,'Ataliva Roca'),
(10,'Bernardo Larroude'),
(10,'Bernasconi'),
(10,'Caleufú'),
(10,'Carro Quemado'),
(10,'Catriló'),
(10,'Ceballos'),
(10,'Chacharramendi'),
(10,'Col. Barón'),
(10,'Col. Santa María'),
(10,'Conhelo'),
(10,'Coronel Hilario Lagos'),
(10,'Cuchillo-Có'),
(10,'Doblas'),
(10,'Dorila'),
(10,'Eduardo Castex'),
(10,'Embajador Martini'),
(10,'Falucho'),
(10,'Gral. Acha'),
(10,'Gral. Manuel Campos'),
(10,'Gral. Pico'),
(10,'Guatraché'),
(10,'Ing. Luiggi'),
(10,'Intendente Alvear'),
(10,'Jacinto Arauz'),
(10,'La Adela'),
(10,'La Humada'),
(10,'La Maruja'),
(10,'La Reforma'),
(10,'Limay Mahuida'),
(10,'Lonquimay'),
(10,'Loventuel'),
(10,'Luan Toro'),
(10,'Macachín'),
(10,'Maisonnave'),
(10,'Mauricio Mayer'),
(10,'Metileo'),
(10,'Miguel Cané'),
(10,'Miguel Riglos'),
(10,'Monte Nievas'),
(10,'Parera'),
(10,'Perú'),
(10,'Pichi-Huinca'),
(10,'Puelches'),
(10,'Puelén'),
(10,'Quehue'),
(10,'Quemú Quemú'),
(10,'Quetrequén'),
(10,'Rancul'),
(10,'Realicó'),
(10,'Relmo'),
(10,'Rolón'),
(10,'Rucanelo'),
(10,'Sarah'),
(10,'Speluzzi'),
(10,'Sta. Isabel'),
(10,'Sta. Rosa'),
(10,'Sta. Teresa'),
(10,'Telén'),
(10,'Toay'),
(10,'Tomas M. de Anchorena'),
(10,'Trenel'),
(10,'Unanue'),
(10,'Uriburu'),
(10,'Veinticinco de Mayo'),
(10,'Vertiz'),
(10,'Victorica'),
(10,'Villa Mirasol'),
(10,'Winifreda')
GO

INSERT INTO localidad (idProvincia,nombre) VALUES -- LA RIOJA
(11,'Arauco'),
(11,'Capital'),
(11,'Castro Barros'),
(11,'Chamical'),
(11,'Chilecito'),
(11,'Coronel F. Varela'),
(11,'Famatina'),
(11,'Gral. A.V.Peñaloza'),
(11,'Gral. Belgrano'),
(11,'Gral. J.F. Quiroga'),
(11,'Gral. Lamadrid'),
(11,'Gral. Ocampo'),
(11,'Gral. San Martín'),
(11,'Independencia'),
(11,'Rosario Penaloza'),
(11,'San Blas de Los Sauces'),
(11,'Sanagasta'),
(11,'Vinchina')
GO

INSERT INTO localidad (idProvincia,nombre) VALUES -- MENDOZA
(12, 'Capital'),
(12, 'Chacras de Coria'),
(12, 'Dorrego'),
(12, 'Gllen'),
(12, 'Godoy Cruz'),
(12, 'Gral. Alvear'),
(12, 'Guaymallén'),
(12, 'Junín'),
(12, 'La Paz'),
(12, 'Las Heras'),
(12, 'Lavalle'),
(12, 'Luján'),
(12, 'Luján De Cuyo'),
(12, 'Maipú'),
(12, 'Malargüe'),
(12, 'Rivadavia'),
(12, 'San Carlos'),
(12, 'San Martín'),
(12, 'San Rafael'),
(12, 'Sta. Rosa'),
(12, 'Tunuyán'),
(12, 'Tupungato'),
(12, 'Villa Nueva')
GO


INSERT INTO localidad (idProvincia,nombre) VALUES -- MISIONES
(13, 'Alba Posse'),
(13, 'Almafuerte'),
(13, 'Apóstoles'),
(13, 'Aristóbulo Del Valle'),
(13, 'Arroyo Del Medio'),
(13, 'Azara'),
(13, 'Bdo. De Irigoyen'),
(13, 'Bonpland'),
(13, 'Caá Yari'),
(13, 'Campo Grande'),
(13, 'Campo Ramón'),
(13, 'Campo Viera'),
(13, 'Candelaria'),
(13, 'Capioví'),
(13, 'Caraguatay'),
(13, 'Cdte. Guacurarí'),
(13, 'Cerro Azul'),
(13, 'Cerro Corá'),
(13, 'Col. Alberdi'),
(13, 'Col. Aurora'),
(13, 'Col. Delicia'),
(13, 'Col. Polana'),
(13, 'Col. Victoria'),
(13, 'Col. Wanda'),
(13, 'Concepción De La Sierra'),
(13, 'Corpus'),
(13, 'Dos Arroyos'),
(13, 'Dos de Mayo'),
(13, 'El Alcázar'),
(13, 'El Dorado'),
(13, 'El Soberbio'),
(13, 'Esperanza'),
(13, 'F. Ameghino'),
(13, 'Fachinal'),
(13, 'Garuhapé'),
(13, 'Garupá'),
(13, 'Gdor. López'),
(13, 'Gdor. Roca'),
(13, 'Gral. Alvear'),
(13, 'Gral. Urquiza'),
(13, 'Guaraní'),
(13, 'H. Yrigoyen'),
(13, 'Iguazú'),
(13, 'Itacaruaré'),
(13, 'Jardín América'),
(13, 'Leandro N. Alem'),
(13, 'Libertad'),
(13, 'Loreto'),
(13, 'Los Helechos'),
(13, 'Mártires'),
(13, 'Mojón Grande'),
(13, 'Montecarlo'),
(13, 'Nueve de Julio'),
(13, 'Oberá'),
(13, 'Olegario V. Andrade'),
(13, 'Panambí'),
(13, 'Posadas'),
(13, 'Profundidad'),
(13, 'Pto. Iguazú'),
(13, 'Pto. Leoni'),
(13, 'Pto. Piray'),
(13, 'Pto. Rico'),
(13, 'Ruiz de Montoya'),
(13, 'San Antonio'),
(13, 'San Ignacio'),
(13, 'San Javier'),
(13, 'San José'),
(13, 'San Martín'),
(13, 'San Pedro'),
(13, 'San Vicente'),
(13, 'Santiago De Liniers'),
(13, 'Santo Pipo'),
(13, 'Sta. Ana'),
(13, 'Sta. María'),
(13, 'Tres Capones'),
(13, 'Veinticinco de Mayo'),
(13, 'Wanda')
GO

INSERT INTO localidad (idProvincia,nombre) VALUES -- NEUQUEN
(14,'Aguada San Roque'),
(14,'Aluminé'),
(14,'Andacollo'),
(14,'Añelo'),
(14,'Bajada del Agrio'),
(14,'Barrancas'),
(14,'Buta Ranquil'),
(14,'Capital'),
(14,'Caviahué'),
(14,'Centenario'),
(14,'Chorriaca'),
(14,'Chos Malal'),
(14,'Cipolletti'),
(14,'Covunco Abajo'),
(14,'Coyuco Cochico'),
(14,'Cutral Có'),
(14,'El Cholar'),
(14,'El Huecú'),
(14,'El Sauce'),
(14,'Guañacos'),
(14,'Huinganco'),
(14,'Las Coloradas'),
(14,'Las Lajas'),
(14,'Las Ovejas'),
(14,'Loncopué'),
(14,'Los Catutos'),
(14,'Los Chihuidos'),
(14,'Los Miches'),
(14,'Manzano Amargo'),
(14,'Octavio Pico'),
(14,'Paso Aguerre'),
(14,'Picún Leufú'),
(14,'Piedra del Aguila'),
(14,'Pilo Lil'),
(14,'Plaza Huincul'),
(14,'Plottier'),
(14,'Quili Malal'),
(14,'Ramón Castro'),
(14,'Rincón de Los Sauces'),
(14,'San Martín de Los Andes'),
(14,'San Patricio del Chañar'),
(14,'Santo Tomás'),
(14,'Sauzal Bonito'),
(14,'Senillosa'),
(14,'Taquimilán'),
(14,'Tricao Malal'),
(14,'Varvarco'),
(14,'Villa Curí Leuvu'),
(14,'Villa del Nahueve'),
(14,'Villa del Puente Picún Leuvú'),
(14,'Villa El Chocón'),
(14,'Villa La Angostura'),
(14,'Villa Pehuenia'),
(14,'Villa Traful'),
(14,'Vista Alegre'),
(14,'Zapala')
GO

INSERT INTO localidad (idProvincia,nombre) VALUES -- RIO NEGRO
(15,'Aguada Cecilio'),
(15,'Aguada de Guerra'),
(15,'Allén'),
(15,'Arroyo de La Ventana'),
(15,'Arroyo Los Berros'),
(15,'Bariloche'),
(15,'Calte. Cordero'),
(15,'Campo Grande'),
(15,'Catriel'),
(15,'Cerro Policía'),
(15,'Cervantes'),
(15,'Chelforo'),
(15,'Chimpay'),
(15,'Chinchinales'),
(15,'Chipauquil'),
(15,'Choele Choel'),
(15,'Cinco Saltos'),
(15,'Cipolletti'),
(15,'Clemente Onelli'),
(15,'Colán Conhue'),
(15,'Comallo'),
(15,'Comicó'),
(15,'Cona Niyeu'),
(15,'Coronel Belisle'),
(15,'Cubanea'),
(15,'Darwin'),
(15,'Dina Huapi'),
(15,'El Bolsón'),
(15,'El Caín'),
(15,'El Manso'),
(15,'Gral. Conesa'),
(15,'Gral. Enrique Godoy'),
(15,'Gral. Fernandez Oro'),
(15,'Gral. Roca'),
(15,'Guardia Mitre'),
(15,'Ing. Huergo'),
(15,'Ing. Jacobacci'),
(15,'Laguna Blanca'),
(15,'Lamarque'),
(15,'Las Grutas'),
(15,'Los Menucos'),
(15,'Luis Beltrán'),
(15,'Mainqué'),
(15,'Mamuel Choique'),
(15,'Maquinchao'),
(15,'Mencué'),
(15,'Mtro. Ramos Mexia'),
(15,'Nahuel Niyeu'),
(15,'Naupa Huen'),
(15,'Ñorquinco'),
(15,'Ojos de Agua'),
(15,'Paso de Agua'),
(15,'Paso Flores'),
(15,'Peñas Blancas'),
(15,'Pichi Mahuida'),
(15,'Pilcaniyeu'),
(15,'Pomona'),
(15,'Prahuaniyeu'),
(15,'Rincón Treneta'),
(15,'Río Chico'),
(15,'Río Colorado'),
(15,'Roca'),
(15,'San Antonio Oeste'),
(15,'San Javier'),
(15,'Sierra Colorada'),
(15,'Sierra Grande'),
(15,'Sierra Pailemán'),
(15,'Valcheta'),
(15,'Valle Azul'),
(15,'Viedma'),
(15,'Villa Llanquín'),
(15,'Villa Mascardi'),
(15,'Villa Regina'),
(15,'Yaminué')
GO


INSERT INTO localidad (idProvincia,nombre) VALUES -- SALTA
(16,'A. Saravia'),
(16,'Aguaray'),
(16,'Angastaco'),
(16,'Animaná'),
(16,'Cachi'),
(16,'Cafayate'),
(16,'Campo Quijano'),
(16,'Campo Santo'),
(16,'Capital'),
(16,'Cerrillos'),
(16,'Chicoana'),
(16,'Col. Sta. Rosa'),
(16,'Coronel Moldes'),
(16,'El Bordo'),
(16,'El Carril'),
(16,'El Galpón'),
(16,'El Jardín'),
(16,'El Potrero'),
(16,'El Quebrachal'),
(16,'El Tala'),
(16,'Embarcación'),
(16,'Gral. Ballivian'),
(16,'Gral. Güemes'),
(16,'Gral. Mosconi'),
(16,'Gral. Pizarro'),
(16,'Guachipas'),
(16,'Hipólito Yrigoyen'),
(16,'Iruyá'),
(16,'Isla De Cañas'),
(16,'J. V. Gonzalez'),
(16,'La Caldera'),
(16,'La Candelaria'),
(16,'La Merced'),
(16,'La Poma'),
(16,'La Viña'),
(16,'Las Lajitas'),
(16,'Los Toldos'),
(16,'Metán'),
(16,'Molinos'),
(16,'Nazareno'),
(16,'Orán'),
(16,'Payogasta'),
(16,'Pichanal'),
(16,'Prof. S. Mazza'),
(16,'Río Piedras'),
(16,'Rivadavia Banda Norte'),
(16,'Rivadavia Banda Sur'),
(16,'Rosario de La Frontera'),
(16,'Rosario de Lerma'),
(16,'Saclantás'),
(16,'San Antonio'),
(16,'San Carlos'),
(16,'San José De Metán'),
(16,'San Ramón'),
(16,'Santa Victoria E.'),
(16,'Santa Victoria O.'),
(16,'Tartagal'),
(16,'Tolar Grande'),
(16,'Urundel'),
(16,'Vaqueros'),
(16,'Villa San Lorenzo')
GO

INSERT INTO localidad (idProvincia,nombre) VALUES -- SAN JUAN
(17,'Albardón'),
(17,'Angaco'),
(17,'Calingasta'),
(17,'Capital'),
(17,'Caucete'),
(17,'Chimbas'),
(17,'Iglesia'),
(17,'Jachal'),
(17,'Nueve de Julio'),
(17,'Pocito'),
(17,'Rawson'),
(17,'Rivadavia'),
(17,'San Martín'),
(17,'Santa Lucía'),
(17,'Sarmiento'),
(17,'Ullum'),
(17,'Valle Fértil'),
(17,'Veinticinco de Mayo'),
(17,'Zonda')
GO


INSERT INTO localidad (idProvincia,nombre) VALUES -- SAN LUIS
(18,'Alto Pelado'),
(18,'Alto Pencoso'),
(18,'Anchorena'),
(18,'Arizona'),
(18,'Bagual'),
(18,'Balde'),
(18,'Batavia'),
(18,'Beazley'),
(18,'Buena Esperanza'),
(18,'Candelaria'),
(18,'Capital'),
(18,'Carolina'),
(18,'Carpintería'),
(18,'Concarán'),
(18,'Cortaderas'),
(18,'El Morro'),
(18,'El Trapiche'),
(18,'El Volcán'),
(18,'Fortín El Patria'),
(18,'Fortuna'),
(18,'Fraga'),
(18,'Juan Jorba'),
(18,'Juan Llerena'),
(18,'Juana Koslay'),
(18,'Justo Daract'),
(18,'La Calera'),
(18,'La Florida'),
(18,'La Punilla'),
(18,'La Toma'),
(18,'Lafinur'),
(18,'Las Aguadas'),
(18,'Las Chacras'),
(18,'Las Lagunas'),
(18,'Las Vertientes'),
(18,'Lavaisse'),
(18,'Leandro N. Alem'),
(18,'Los Molles'),
(18,'Luján'),
(18,'Mercedes'),
(18,'Merlo'),
(18,'Naschel'),
(18,'Navia'),
(18,'Nogolí'),
(18,'Nueva Galia'),
(18,'Papagayos'),
(18,'Paso Grande'),
(18,'Potrero de Los Funes'),
(18,'Quines'),
(18,'Renca'),
(18,'Saladillo'),
(18,'San Francisco'),
(18,'San Gerónimo'),
(18,'San Martín'),
(18,'San Pablo'),
(18,'Santa Rosa de Conlara'),
(18,'Talita'),
(18,'Tilisarao'),
(18,'Unión'),
(18,'Villa de La Quebrada'),
(18,'Villa de Praga'),
(18,'Villa del Carmen'),
(18,'Villa Gral. Roca'),
(18,'Villa Larca'),
(18,'Villa Mercedes'),
(18,'Zanjitas')
GO
INSERT INTO localidad (idProvincia,nombre) VALUES -- SANTA CRUZ
(19, 'Calafate'),
(19, 'Caleta Olivia'),
(19, 'Cañadón Seco'),
(19, 'Comandante Piedrabuena'),
(19, 'El Calafate'),
(19, 'El Chaltén'),
(19, 'Gdor. Gregores'),
(19, 'Hipólito Yrigoyen'),
(19, 'Jaramillo'),
(19, 'Koluel Kaike'),
(19, 'Las Heras'),
(19, 'Los Antiguos'),
(19, 'Perito Moreno'),
(19, 'Pico Truncado'),
(19, 'Pto. Deseado'),
(19, 'Pto. San Julián'),
(19, 'Pto. 21'),
(19, 'Río Cuarto'),
(19, 'Río Gallegos'),
(19, 'Río Turbio'),
(19, 'Tres Lagos'),
(19, 'Veintiocho De Noviembre')
GO

INSERT INTO localidad (idProvincia,nombre) VALUES -- SANTA FE
(20,'Aarón Castellanos'),
(20,'Acebal'),
(20,'Aguará Grande'),
(20,'Albarellos'),
(20,'Alcorta'),
(20,'Aldao'),
(20,'Alejandra'),
(20,'Álvarez'),
(20,'Ambrosetti'),
(20,'Amenábar'),
(20,'Angélica'),
(20,'Angeloni'),
(20,'Arequito'),
(20,'Arminda'),
(20,'Armstrong'),
(20,'Arocena'),
(20,'Arroyo Aguiar'),
(20,'Arroyo Ceibal'),
(20,'Arroyo Leyes'),
(20,'Arroyo Seco'),
(20,'Arrufó'),
(20,'Arteaga'),
(20,'Ataliva'),
(20,'Aurelia'),
(20,'Avellaneda'),
(20,'Barrancas'),
(20,'Bauer Y Sigel'),
(20,'Bella Italia'),
(20,'Berabevú'),
(20,'Berna'),
(20,'Bernardo de Irigoyen'),
(20,'Bigand'),
(20,'Bombal'),
(20,'Bouquet'),
(20,'Bustinza'),
(20,'Cabal'),
(20,'Cacique Ariacaiquin'),
(20,'Cafferata'),
(20,'Calchaquí'),
(20,'Campo Andino'),
(20,'Campo Piaggio'),
(20,'Cañada de Gómez'),
(20,'Cañada del Ucle'),
(20,'Cañada Rica'),
(20,'Cañada Rosquín'),
(20,'Candioti'),
(20,'Capital'),
(20,'Capitán Bermúdez'),
(20,'Capivara'),
(20,'Carcarañá'),
(20,'Carlos Pellegrini'),
(20,'Carmen'),
(20,'Carmen Del Sauce'),
(20,'Carreras'),
(20,'Carrizales'),
(20,'Casalegno'),
(20,'Casas'),
(20,'Casilda'),
(20,'Castelar'),
(20,'Castellanos'),
(20,'Cayastá'),
(20,'Cayastacito'),
(20,'Centeno'),
(20,'Cepeda'),
(20,'Ceres'),
(20,'Chabás'),
(20,'Chañar Ladeado'),
(20,'Chapuy'),
(20,'Chovet'),
(20,'Christophersen'),
(20,'Classon'),
(20,'Cnel. Arnold'),
(20,'Cnel. Bogado'),
(20,'Cnel. Dominguez'),
(20,'Cnel. Fraga'),
(20,'Col. Aldao'),
(20,'Col. Ana'),
(20,'Col. Belgrano'),
(20,'Col. Bicha'),
(20,'Col. Bigand'),
(20,'Col. Bossi'),
(20,'Col. Cavour'),
(20,'Col. Cello'),
(20,'Col. Dolores'),
(20,'Col. Dos Rosas'),
(20,'Col. Durán'),
(20,'Col. Iturraspe'),
(20,'Col. Margarita'),
(20,'Col. Mascias'),
(20,'Col. Raquel'),
(20,'Col. Rosa'),
(20,'Col. San José'),
(20,'Constanza'),
(20,'Coronda'),
(20,'Correa'),
(20,'Crispi'),
(20,'Cululú'),
(20,'Curupayti'),
(20,'Desvio Arijón'),
(20,'Diaz'),
(20,'Diego de Alvear'),
(20,'Egusquiza'),
(20,'El Arazá'),
(20,'El Rabón'),
(20,'El Sombrerito'),
(20,'El Trébol'),
(20,'Elisa'),
(20,'Elortondo'),
(20,'Emilia'),
(20,'Empalme San Carlos'),
(20,'Empalme Villa Constitucion'),
(20,'Esmeralda'),
(20,'Esperanza'),
(20,'Estación Alvear'),
(20,'Estacion Clucellas'),
(20,'Esteban Rams'),
(20,'Esther'),
(20,'Esustolia'),
(20,'Eusebia'),
(20,'Felicia'),
(20,'Fidela'),
(20,'Fighiera'),
(20,'Firmat'),
(20,'Florencia'),
(20,'Fortín Olmos'),
(20,'Franck'),
(20,'Fray Luis Beltrán'),
(20,'Frontera'),
(20,'Fuentes'),
(20,'Funes'),
(20,'Gaboto'),
(20,'Galisteo'),
(20,'Gálvez'),
(20,'Garabalto'),
(20,'Garibaldi'),
(20,'Gato Colorado'),
(20,'Gdor. Crespo'),
(20,'Gessler'),
(20,'Godoy'),
(20,'Golondrina'),
(20,'Gral. Gelly'),
(20,'Gral. Lagos'),
(20,'Granadero Baigorria'),
(20,'Gregoria Perez De Denis'),
(20,'Grutly'),
(20,'Guadalupe N.'),
(20,'Gödeken'),
(20,'Helvecia'),
(20,'Hersilia'),
(20,'Hipatía'),
(20,'Huanqueros'),
(20,'Hugentobler'),
(20,'Hughes'),
(20,'Humberto 1º'),
(20,'Humboldt'),
(20,'Ibarlucea'),
(20,'Ing. Chanourdie'),
(20,'Intiyaco'),
(20,'Ituzaingó'),
(20,'Jacinto L. Aráuz'),
(20,'Josefina'),
(20,'Juan B. Molina'),
(20,'Juan de Garay'),
(20,'Juncal'),
(20,'La Brava'),
(20,'La Cabral'),
(20,'La Camila'),
(20,'La Chispa'),
(20,'La Clara'),
(20,'La Criolla'),
(20,'La Gallareta'),
(20,'La Lucila'),
(20,'La Pelada'),
(20,'La Penca'),
(20,'La Rubia'),
(20,'La Sarita'),
(20,'La Vanguardia'),
(20,'Labordeboy'),
(20,'Laguna Paiva'),
(20,'Landeta'),
(20,'Lanteri'),
(20,'Larrechea'),
(20,'Las Avispas'),
(20,'Las Bandurrias'),
(20,'Las Garzas'),
(20,'Las Palmeras'),
(20,'Las Parejas'),
(20,'Las Petacas'),
(20,'Las Rosas'),
(20,'Las Toscas'),
(20,'Las Tunas'),
(20,'Lazzarino'),
(20,'Lehmann'),
(20,'Llambi Campbell'),
(20,'Logroño'),
(20,'Loma Alta'),
(20,'López'),
(20,'Los Amores'),
(20,'Los Cardos'),
(20,'Los Laureles'),
(20,'Los Molinos'),
(20,'Los Quirquinchos'),
(20,'Lucio V. Lopez'),
(20,'Luis Palacios'),
(20,'Ma. Juana'),
(20,'Ma. Luisa'),
(20,'Ma. Susana'),
(20,'Ma. Teresa'),
(20,'Maciel'),
(20,'Maggiolo'),
(20,'Malabrigo'),
(20,'Marcelino Escalada'),
(20,'Margarita'),
(20,'Matilde'),
(20,'Mauá'),
(20,'Máximo Paz'),
(20,'Melincué'),
(20,'Miguel Torres'),
(20,'Moisés Ville'),
(20,'Monigotes'),
(20,'Monje'),
(20,'Monte Obscuridad'),
(20,'Monte Vera'),
(20,'Montefiore'),
(20,'Montes de Oca'),
(20,'Murphy'),
(20,'Ñanducita'),
(20,'Naré'),
(20,'Nelson'),
(20,'Nicanor E. Molinas'),
(20,'Nuevo Torino'),
(20,'Oliveros'),
(20,'Palacios'),
(20,'Pavón'),
(20,'Pavón Arriba'),
(20,'Pedro Gómez Cello'),
(20,'Pérez'),
(20,'Peyrano'),
(20,'Piamonte'),
(20,'Pilar'),
(20,'Piñero'),
(20,'Plaza Clucellas'),
(20,'Portugalete'),
(20,'Pozo Borrado'),
(20,'Progreso'),
(20,'Providencia'),
(20,'Pte. Roca'),
(20,'Pueblo Andino'),
(20,'Pueblo Esther'),
(20,'Pueblo Gral. San Martín'),
(20,'Pueblo Irigoyen'),
(20,'Pueblo Marini'),
(20,'Pueblo Muñoz'),
(20,'Pueblo Uranga'),
(20,'Pujato'),
(20,'Pujato N.'),
(20,'Rafaela'),
(20,'Ramayón'),
(20,'Ramona'),
(20,'Reconquista'),
(20,'Recreo'),
(20,'Ricardone'),
(20,'Rivadavia'),
(20,'Roldán'),
(20,'Romang'),
(20,'Rosario'),
(20,'Rueda'),
(20,'Rufino'),
(20,'Sa Pereira'),
(20,'Saguier'),
(20,'Saladero M. Cabal'),
(20,'Salto Grande'),
(20,'San Agustín'),
(20,'San Antonio de Obligado'),
(20,'San Bernardo (N.J.)'),
(20,'San Bernardo (S.J.)'),
(20,'San Carlos Centro'),
(20,'San Carlos N.'),
(20,'San Carlos S.'),
(20,'San Cristóbal'),
(20,'San Eduardo'),
(20,'San Eugenio'),
(20,'San Fabián'),
(20,'San Fco. de Santa Fé'),
(20,'San Genaro'),
(20,'San Genaro N.'),
(20,'San Gregorio'),
(20,'San Guillermo'),
(20,'San Javier'),
(20,'San Jerónimo del Sauce'),
(20,'San Jerónimo N.'),
(20,'San Jerónimo S.'),
(20,'San Jorge'),
(20,'San José de La Esquina'),
(20,'San José del Rincón'),
(20,'San Justo'),
(20,'San Lorenzo'),
(20,'San Mariano'),
(20,'San Martín de Las Escobas'),
(20,'San Martín N.'),
(20,'San Vicente'),
(20,'Sancti Spititu'),
(20,'Sanford'),
(20,'Santo Domingo'),
(20,'Santo Tomé'),
(20,'Santurce'),
(20,'Sargento Cabral'),
(20,'Sarmiento'),
(20,'Sastre'),
(20,'Sauce Viejo'),
(20,'Serodino'),
(20,'Silva'),
(20,'Soldini'),
(20,'Soledad'),
(20,'Soutomayor'),
(20,'Sta. Clara de Buena Vista'),
(20,'Sta. Clara de Saguier'),
(20,'Sta. Isabel'),
(20,'Sta. Margarita'),
(20,'Sta. Maria Centro'),
(20,'Sta. María N.'),
(20,'Sta. Rosa'),
(20,'Sta. Teresa'),
(20,'Suardi'),
(20,'Sunchales'),
(20,'Susana'),
(20,'Tacuarendí'),
(20,'Tacural'),
(20,'Tartagal'),
(20,'Teodelina'),
(20,'Theobald'),
(20,'Timbúes'),
(20,'Toba'),
(20,'Tortugas'),
(20,'Tostado'),
(20,'Totoras'),
(20,'Traill'),
(20,'Venado Tuerto'),
(20,'Vera'),
(20,'Vera y Pintado'),
(20,'Videla'),
(20,'Vila'),
(20,'Villa Amelia'),
(20,'Villa Ana'),
(20,'Villa Cañas'),
(20,'Villa Constitución'),
(20,'Villa Eloísa'),
(20,'Villa Gdor. Gálvez'),
(20,'Villa Guillermina'),
(20,'Villa Minetti'),
(20,'Villa Mugueta'),
(20,'Villa Ocampo'),
(20,'Villa San José'),
(20,'Villa Saralegui'),
(20,'Villa Trinidad'),
(20,'Villada'),
(20,'Virginia'),
(20,'Wheelwright'),
(20,'Zavalla'),
(20,'Zenón Pereira')
GO


INSERT INTO localidad (idProvincia,nombre) VALUES -- SANTIAGO DEL ESTERO
(21, 'Añatuya'),
(21, 'Árraga'),
(21, 'Bandera'),
(21, 'Bandera Bajada'),
(21, 'Beltrán'),
(21, 'Brea Pozo'),
(21, 'Campo Gallo'),
(21, 'Capital'),
(21, 'Chilca Juliana'),
(21, 'Choya'),
(21, 'Clodomira'),
(21, 'Col. Alpina'),
(21, 'Col. Dora'),
(21, 'Col. El Simbolar Robles'),
(21, 'El Bobadal'),
(21, 'El Charco'),
(21, 'El Mojón'),
(21, 'Estación Atamisqui'),
(21, 'Estación Simbolar'),
(21, 'Fernández'),
(21, 'Fortín Inca'),
(21, 'Frías'),
(21, 'Garza'),
(21, 'Gramilla'),
(21, 'Guardia Escolta'),
(21, 'Herrera'),
(21, 'Icaño'),
(21, 'Ing. Forres'),
(21, 'La Banda'),
(21, 'La Cañada'),
(21, 'Laprida'),
(21, 'Lavalle'),
(21, 'Loreto'),
(21, 'Los Juríes'),
(21, 'Los Núñez'),
(21, 'Los Pirpintos'),
(21, 'Los Quiroga'),
(21, 'Los Telares'),
(21, 'Lugones'),
(21, 'Malbrán'),
(21, 'Matara'),
(21, 'Medellín'),
(21, 'Monte Quemado'),
(21, 'Nueva Esperanza'),
(21, 'Nueva Francia'),
(21, 'Palo Negro'),
(21, 'Pampa de Los Guanacos'),
(21, 'Pinto'),
(21, 'Pozo Hondo'),
(21, 'Quimilí'),
(21, 'Real Sayana'),
(21, 'Sachayoj'),
(21, 'San Pedro de Guasayán'),
(21, 'Selva'),
(21, 'Sol de Julio'),
(21, 'Sumampa'),
(21, 'Suncho Corral'),
(21, 'Taboada'),
(21, 'Tapso'),
(21, 'Termas de Rio Hondo'),
(21, 'Tintina'),
(21, 'Tomas Young'),
(21, 'Vilelas'),
(21, 'Villa Atamisqui'),
(21, 'Villa La Punta'),
(21, 'Villa Ojo de Agua'),
(21, 'Villa Río Hondo'),
(21, 'Villa Salavina'),
(21, 'Villa Unión'),
(21, 'Vilmer'),
(21, 'Weisburd')
GO


INSERT INTO localidad (idProvincia,nombre) VALUES -- TIERRA DEL FUEGO
(22,'Río Grande'),
(22,'Tolhuin'),
(22,'Ushuaia')
GO

INSERT INTO localidad (idProvincia,nombre) VALUES -- TUCUMAN
(23, 'Acheral'),
(23, 'Agua Dulce'),
(23, 'Aguilares'),
(23, 'Alderetes'),
(23, 'Alpachiri'),
(23, 'Alto Verde'),
(23, 'Amaicha del Valle'),
(23, 'Amberes'),
(23, 'Ancajuli'),
(23, 'Arcadia'),
(23, 'Atahona'),
(23, 'Banda del Río Sali'),
(23, 'Bella Vista'),
(23, 'Buena Vista'),
(23, 'Burruyacú'),
(23, 'Capitán Cáceres'),
(23, 'Cevil Redondo'),
(23, 'Choromoro'),
(23, 'Ciudacita'),
(23, 'Colalao del Valle'),
(23, 'Colombres'),
(23, 'Concepción'),
(23, 'Delfín Gallo'),
(23, 'El Bracho'),
(23, 'El Cadillal'),
(23, 'El Cercado'),
(23, 'El Chañar'),
(23, 'El Manantial'),
(23, 'El Mojón'),
(23, 'El Mollar'),
(23, 'El Naranjito'),
(23, 'El Naranjo'),
(23, 'El Polear'),
(23, 'El Puestito'),
(23, 'El Sacrificio'),
(23, 'El Timbó'),
(23, 'Escaba'),
(23, 'Esquina'),
(23, 'Estación Aráoz'),
(23, 'Famaillá'),
(23, 'Gastone'),
(23, 'Gdor. Garmendia'),
(23, 'Gdor. Piedrabuena'),
(23, 'Graneros'),
(23, 'Huasa Pampa'),
(23, 'J. B. Alberdi'),
(23, 'La Cocha'),
(23, 'La Esperanza'),
(23, 'La Florida'),
(23, 'La Ramada'),
(23, 'La Trinidad'),
(23, 'Lamadrid'),
(23, 'Las Cejas'),
(23, 'Las Talas'),
(23, 'Las Talitas'),
(23, 'Los Bulacio'),
(23, 'Los Gómez'),
(23, 'Los Nogales'),
(23, 'Los Pereyra'),
(23, 'Los Pérez'),
(23, 'Los Puestos'),
(23, 'Los Ralos'),
(23, 'Los Sarmientos'),
(23, 'Los Sosa'),
(23, 'Lules'),
(23, 'M. García Fernández'),
(23, 'Manuela Pedraza'),
(23, 'Medinas'),
(23, 'Monte Bello'),
(23, 'Monteagudo'),
(23, 'Monteros'),
(23, 'Padre Monti'),
(23, 'Pampa Mayo'),
(23, 'Quilmes'),
(23, 'Raco'),
(23, 'Ranchillos'),
(23, 'Río Chico'),
(23, 'Río Colorado'),
(23, 'Río Seco'),
(23, 'Rumi Punco'),
(23, 'San Andrés'),
(23, 'San Felipe'),
(23, 'San Ignacio'),
(23, 'San Javier'),
(23, 'San José'),
(23, 'San Miguel de 25'),
(23, 'San Pedro'),
(23, 'San Pedro de Colalao'),
(23, 'Santa Rosa de Leales'),
(23, 'Sgto. Moya'),
(23, 'Siete de Abril'),
(23, 'Simoca'),
(23, 'Soldado Maldonado'),
(23, 'Sta. Ana'),
(23, 'Sta. Cruz'),
(23, 'Sta. Lucía'),
(23, 'Taco Ralo'),
(23, 'Tafí del Valle'),
(23, 'Tafí Viejo'),
(23, 'Tapia'),
(23, 'Teniente Berdina'),
(23, 'Trancas'),
(23, 'Villa Belgrano'),
(23, 'Villa Benjamín Araoz'),
(23, 'Villa Chiligasta'),
(23, 'Villa de Leales'),
(23, 'Villa Quinteros'),
(23, 'Yánima'),
(23, 'Yerba Buena'),
(23, 'Yerba Buena (S)')
GO