INSERT INTO plato (idPlato, nombrePlato, imagenPlato, preparacion, idMenu)
VALUES
(1, 'Tortilla de Verduras', './../../../assets/img/menu/lunes/tortilla_verdura.jpg', 'Bata los huevos con pimienta, orégano o albahaca, y queso en un cuenco o tazón mediano.
                                                                                                         Caliente el aceite en una sartén medio. Añada cebolla, ajo, y otros vegetales y cocínelos a fuego medio
                                                                                                         (300 grados F en una sartén eléctrica) hasta que estén tiernos.
                                                                                                         Ponga la mezcla de huevos sobre los vegetales. Con el cuchillo o la espátula,
                                                                                                         levante los bordes de los huevos para que la mezcla se mueva fácilmente en el fondo de la sartén.
                                                                                                         Cocine hasta que los huevos estén cocinados a su gusto, más o menos 6 minutos. Ponga encima rebanadas de tomate.
                                                                                                         Corte en 8 pedazos; sirva caliente.
                                                                                                         Refrigere lo que sobre dentro de las siguientes 2 horas.', 1 )
, (2, 'Panqueques de Pollo', './../../../assets/img/menu/martes/panqueques_de_pollo.jpg', '– Lavar la pechuga de pollo y poner en una olla con 4 tazas de agua.
                                                                                                              Sazonar con sal, pimienta, orégano y aliños de su gusto. Cocinar a fuego alto hasta que hierva,
                                                                                                               reducir el calor y cocinar tapado 20-25 minutos o hasta que el pollo esté cocido.
                                                                                                               Retirar el pollo de la olla, colar y reservar el caldo para usarlo más adelante.
                                                                                                              – Eliminar la piel del pollo, enfriar ligeramente, desmenuzar y reservar.
                                                                                                              – En un recipiente, añadir la leche, 1 taza de agua, 3 huevos y 1 taza de harina.
                                                                                                              Batir para incorporar todos los ingredientes y colar a otro recipiente.
                                                                                                              – Calentar un sartén de unos 20 cm de diámetro y con la ayuda de un papel absorbente pintar
                                                                                                              el fondo con aceite. Agregar 1/2 taza de la mezcla de panqueque y mover rápidamente el sartén
                                                                                                              para esparcir la mezcla por todo el fondo. Cocinar 2-3 minutos hasta dorar, dar vuelta y cocinar
                                                                                                              por el otro lado 1-2 minutos también hasta dorar. No dorar mucho para que no queden muy rígidos.
                                                                                                              Repetir el proceso con el resto del batido hasta completar 8 panqueques.
                                                                                                              – Calentar 3 tazas del caldo del pollo a fuego medio hasta hervir.
                                                                                                              – En un bol aparte, poner 3/4 taza de harina y disolver con agua.
                                                                                                              Agregar de a poco el caldo del pollo, revolviendo hasta que la mezcla espese.
                                                                                                              Incorporar la crema, mezclar y sazonar con sal, pimienta, una pizca de orégano,
                                                                                                               2 cucharadas de ají de color y la mitad del queso rallado.
                                                                                                              – Reservar 3 tazas de la mezcla y al resto que queda agregar el pollo desmenuzado y revolver.
                                                                                                              – Rellenar cada uno de los panqueques con 2 -3 cucharadas de la mezcla del pollo.
                                                                                                              – Poner los panqueques rellenados en una fuente de horno,
                                                                                                              cubrir con las 3 tazas de crema reservada, espolvorear con el resto del queso rallado y 1 cucharadita de ají de color.
                                                                                                              – Cocinar en el horno hasta calentar y dorar. Servir caliente 2 panqueques por persona.que tengas en casa', 2 )
,(3, 'Tortilla de Zanahorias', './../../../assets/img/menu/miercoles/tortilla_de_zanahoria.jpg', 'Calentar a fuego medio-alto 1 cucharada de aceite en una sartén mediana
                                                                                                                     anti-adherente, agregar la cebolla picada y dejar dorar por 5-8 minutos hasta que este
                                                                                                                     empezando a cambiar de color.
                                                                                                                     Juntar la cebolla con la zanahoria rallada en un bol y revolver mezclando bien.
                                                                                                                     En un bol pequeño mezclar los huevos con la crema, perejil si desean, sal y pimienta,
                                                                                                                     batir por 2 minutos con un tenedor hasta que este espumoso.
                                                                                                                     En la misma sartén de la cebolla, la pueden limpiar con una toalla de papel (fuera del fuego)
                                                                                                                     calentar 1 cucharada de aceite a fuego medio, agregar la mezcla de zanahoria y cebolla
                                                                                                                     y aplastar bien de manera de cubrir toda la sartén de manera pareja, agregar de inmediato
                                                                                                                     la mezcla de huevos y dejar que escurra. Dejar cocinar la tortilla a fuego medio por unos
                                                                                                                     15 minutos, agitarla de vez en cuando para que no se pegue.
                                                                                                                     Cuando el centro este cocido (deje de estar húmedo) dar vuelta la tortilla,
                                                                                                                     yo lo hago con la ayuda de un plato y dejarla dorar por el otro lado unos 3 minutos mas.
                                                                                                                     Servir caliente o a temperatura ambiente, espolvoreada con ciboulette si desean.
                                                                                                                     Si no quieren dar vuelta la tortilla, pueden usar el broiler del horno para dorarla arriba,     quedan igual de bien. Yo hago eso en mi casa.', 3)
,(4, 'Hummus', './../../../assets/img/menu/jueves/hummus.jpg', 'Podemos usar garbanzos de bote o cocer los garbanzos. Si optamos por esta opción,
                                                                                   tenemos que dejar los garbanzos en remojo entre 8 y 12 horas en abundante agua.
                                                                                   A diferencia de otras legumbres, los garbanzos deben echarse en la olla cuando el agua esté
                                                                                   hirviendo, dejamos cocer durante 2 horas y le añadimos la sal al final.
                                                                                   Escurrimos y dejamos enfriar.
                                                                                   Echamos los garbanzos en una batidora o robot de cocina junto con el zumo de medio limón,
                                                                                   el tahín, el ajo, la sal, el comino y el caldo de cocción (o agua en caso de que los garbanzos
                                                                                    sean de bote) y batimos hasta crear una crema homogénea. Si se desea que el hummus quede
                                                                                    más líquido basta con añadir más caldo o agua.
                                                                                   Para la presentación del hummus vertemos la crema en un plato o cuenco y con una cuchara
                                                                                   creamos surcos en la superficie. Añadimos aceite de oliva virgen extra al gusto, aceitunas
                                                                                   y pimentón dulce para decorarlo. Por último, elegimos el acompañamiento deseado.', 4)
,(5, 'Tallarines alfredo', './../../../assets/img/menu/viernes/tallarines.jpg', 'Cocina los tallarines como los sueles preparar.
                                                                                                    Luego en una olla aparte debes derretir la mantequilla con la leche,
                                                                                                    agregar el queso parmesano rallado y dejar a fuego lento por algunos minutos (revolver al mismo tiempo).
                                                                                                    Después condimenta esta mezcla con sal al gusto y añade el jamón cortado en cuadrados.  Posteriormente agrega la salsa sobre los tallarines y finaliza decorando con perejil si deseas. ¡Provecho!', 5 )
,(6, 'Bistec a la plancha', './../../../assets/img/menu/sabado/bistec_a_la_plancha.jpg', 'Lo primero antes de preparar, debemos sazonar la carne con todos los aliños y
                                                                                                             colocarlo a macerar con la salsa inglesa, por lo menos una media hora antes de cocer.
                                                                                                             Luego colocamos la plancha o la sartén en fuego medio, cuando esté caliente añadimos un chorito minimo
                                                                                                             de aceite y colocamos los filetes a cocinar. Debemos vigilar que doren bien sin llegar a resecarse,
                                                                                                             por eso no debemos subir mucho la llama. Se pueden acompañar con arroz blanco, papas, puré, y una fresca ensalada verde de lechuga, cebolla y tomate.', 6)
,(7, 'Croquetas de Atun', './../../../assets/img/menu/domingo/croquetas_de_atun.jpg', 'Retirar el atún de la lata y escurrir su líquido.
                                                                                                          En un recipiente grande verter el atún, los huevos, el perejil y el pan rallado,
                                                                                                          se salpimienta la preparación y se mezcla muy bien.
                                                                                                          Se agrega harina a la mezcla, hasta crear consistencia.
                                                                                                           Se arman las croquetas y se fríen.', 7)
,(8, 'Espinacas Gratinadas', './../../../assets/img/menu/lunes/espinacas_gratinadas.jpg', 'PRECALIENTA el horno a 180°
                                                                                           MEZCLA todos los ingredientes, reservando un poco de queso manchego rallado.
                                                                                           COLOCA la mezcla de espinacas con queso cottage en un refractario y espolvorea con el queso restante.
                                                                                           HORNEA durante 25 minutos.
                                                                                           SIRVE estas espinacas con queso gratinado para la dieta como plato fuerte acompañado de arroz o como guarnición.', 1 )
,(9, 'Lasagna de berenjena', './../../../assets/img/menu/lunes/lasagna_de_berenjena.jpg', 'Limpiar las berenjenas. Cortar los extremos y partirlas por la mitad. Luego, hacer lonchas no muy finas. Pintar con aceite de oliva por ambas caras y dorar en una sartén. Retirar. Sofría la cebolla hasta que esté dorada pero sin quemarse
                                                                                           Cortar el tomate en dados, picar las hierbas frescas y mezclar todo en un bol. Condimentar con sal marina y aceite de oliva y, en la misma sartén, saltear unos minutos hasta que los tomates se ablanden. Agregar el vinagre, remover unos minutos, y retirar.
                                                                                           Cortar el queso fresco en lonchas.
                                                                                           Para montar el plato, disponer primero una loncha de berenjena, luego una lámina de queso, y finalmente el tomate y la cebolla. Repetir esta operación y decorar con berenjena y tomate.', 1 )
,(10, 'Zapallos rellenos', './../../../assets/img/menu/lunes/zapallos_rellenos.jpg', 'Cocer los zapallos en una olla con abundante agua por unos 10 a 15 minutos. Luego retirar, estilar y dejar enfriar.
                                                                                                En un sartén freír con el aceite el ajo picado y la cebolla en cuadritos. Luego agregar la carne molida. Posteriormente agregar disuelto el caldo y los aliños.
                                                                                                Mientras tanto se cortan los zapallos en dos, para poder sacarle el interior con mucho cuidado de no romper la cáscara. Se muele un poco con un tenedor el interior del zapallo. Luego se agrega esto al sartén con la carne, se revuelve bien y se agregan dos huevos enteros. Una vez listo esto, se colocan las cáscaras en una fuente para ir al horno. Se rellenan los zapallos y encima se coloca queso entero o rallado (suizo, parmesano), luego se lleva al horno hasta que el queso este dorado.
                                                                                                Como acompañamiento, puede ser arroz, puré o lo que su imaginación le diga. Y para completar una rica comida, no puede faltar un buen Vino Gato y en esta ocasión les recomendamos un rico Cabernet Sauvignon.', 1 )
,(11, 'Tartaletas de pollo', './../../../assets/img/menu/martes/tartaletas_de_pollo.jpg', 'En esta receta puedes aprovechar pollo que te haya sobrado de otra comida. Le quitas huesos y piel y los desmigajas en trozos pequeños.Si usas pollo en crudo usa una pechuga grande deshuesada y sin piel. Cortarla primero en filetes y luego cortar tiras longitudinales y por último cortar perpendicularmente formando dados pequeños de carne de pollo.Poner los 2 huevos a cocer cubiertos con agua caliente, cuando hierva bajar al mínimo o apagar si es una vitro y dejar 10-12 minutos. Retirar y enfriar bajo el grifo.Mientras se hacen los huevos picar la cebolla y el pimiento morrón.Echar un poco de aceite en una sartén, cacerola o wok. Cuando esté caliente echar la cebolla y el pimiento y rehogar o sofreír hasta que esté cocido. Retirar.En la misma sartén o wok cocinar el pollo si es que lo tienes crudo. Sellar bien por todos lados.Pelar los huevos y picarlos. Echar sobre el pollo. Añadir el sofrito de cebolla y pimiento y mezclar.Batir el huevo con las 2 cucharadas de leche, echarlo por arriba del relleno.Condimentar con sal, pimienta y si gustas algún otro condimento o hierba aromática. Mezclar todo bien y ya tienes listo el relleno!!Untar un molde para muffins o magdalenas con mantequilla, manteca o pincelar con aceite.Colocar una oblea o tapa de empanada en cada hueco. Yo formo una canastita con cada círculo de masa, hago primero una «pinza»  de cada lado, el doblez lo pego por detrás haciendo presión entre los dedos, hago otras «pinzas» en cruz y vuelvo a pegar el pliegue de masa por detrás. Quedan así como en la foto y de ahí coloco cada uno en el hueco del molde y lo ajusto haciendo coincidir la forma.Una vez que está todo el molde listo con las 12 canastitas de masa colocar el relleno de a cucharadas bien hasta arriba. Es más o menos una cucharada y media en cada uno.Meter al horno precalentado a 190ºC y cocinar las Canastita de Pollo hasta dorar a gusto.Sacar y con mucho cuidado que no se rompan desmoldar, yo uso el mango de una cuchara o tenedor a modo de calzador y levanto cada Canastita de Pollo del molde con cuidado de no romperla.', 2 )
,(12, 'Pollo arvejado', './../../../assets/img/menu/martes/pollo_arvejado.jpg', 'Lavar y retirar la piel del pollo. Reservar en una cacerola, poner las 3 cucharadas de aceite y sofreír ajo y cebolla,
                                                                                 Cuando empiece a blanquear, añadir las presas de pollo y dorar un poco por ambos lados.Añadir los pimientos, zanahorias y tomates. Mezclar y dejar unos minutos a fuego medio para que los ingredientes suelten sus jugos y se integren los sabores.
                                                                                 En este punto, condimentar con el laurel, orégano y pimienta. Añadir el concentrado de pollo y el vino. Revolver o remover la cacerola para que todo quede muy bien integrado.
                                                                                 Una vez que suelte el hervor, tapar y dejar cocer a fuego medio entre 5 a 10 minutos.
                                                                                 Añadir las arvejitas y si fuese necesario, algo de agua para que se complete la cocción sin que se reseque. Verificar la sal y rectificar si fuese necesario.
                                                                                 Una vez que las arvejitas estén blandas, retirar el guiso del fuego.
                                                                                 Si se observa exceso de jugo, puede espesarse con un poco de maicena o harina disuelta en unas cucharadas de agua. Dejar cocinar un par de minutos a fuego bajo.
                                                                                 Acompañamiento:
                                                                                 Freír las papas que teníamos cortadas en cubitos y distribuir una porción en cada plato, junto con una porción de arroz y el pollo bañado con su salsa y verduras.', 2 )